c -c -o -x -i0:b: dwait.c drline.c dkey.c dkeyrun.c dsent.c dconrun.c
libr r b:libdemo.lib dconrun.obj dkeyrun.obj dwait.obj drline.obj dkey.obj dsent.obj
c -o -x -i0:b: vickey.c 0:b:libdemo.lib 0:b:libc3l.lib 0:a:libc.lib
c -o -x -i0:b: vdckey.c 0:b:libdemo.lib 0:b:libc3l.lib 0:a:libc.lib
c -o -x -i0:b: viccon.c 0:b:libdemo.lib 0:b:libc3l.lib 0:a:libc.lib
c -o -x -i0:b: vdccon.c 0:b:libdemo.lib 0:b:libc3l.lib 0:a:libc.lib
